# Generated by Django 6.0 on 2025-12-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="group",
            name="group_code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
