# Generated by Django 6.0 on 2025-12-27 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_group_created_at_remove_group_members_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="paymates_groups",
                related_query_name="paymates_group",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
