# Generated by Django 6.0 on 2025-12-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_settlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="receipt",
            field=models.ImageField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
