# Generated by Django 6.0 on 2026-01-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_notification_friendship"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.DeleteModel(
            name="Friendship",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
