# Generated by Django 6.0 on 2026-01-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="group_pics/"),
        ),
    ]
