# Generated by Django 6.0 on 2026-01-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_groupchatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchatmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chat_images/"),
        ),
        migrations.AlterField(
            model_name="groupchatmessage",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
