# Generated by Django 6.0 on 2026-02-27 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_chatroom_users_alter_notification_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupchatmessage",
            options={"ordering": ["createdat"]},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-createdat"]},
        ),
        migrations.AlterModelOptions(
            name="privatechatmessage",
            options={"ordering": ["createdat"]},
        ),
        migrations.RenameField(
            model_name="chatroom",
            old_name="created_at",
            new_name="createdat",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="created_at",
            new_name="createdat",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="deleted_at",
            new_name="deletedat",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="is_deleted",
            new_name="isdeleted",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="paid_by",
            new_name="paidby",
        ),
        migrations.RenameField(
            model_name="group",
            old_name="group_code",
            new_name="groupcode",
        ),
        migrations.RenameField(
            model_name="groupchatmessage",
            old_name="created_at",
            new_name="createdat",
        ),
        migrations.RenameField(
            model_name="leaverequest",
            old_name="created_at",
            new_name="createdat",
        ),
        migrations.RenameField(
            model_name="leaverequest",
            old_name="decided_at",
            new_name="decidedat",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="created_at",
            new_name="createdat",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="is_read",
            new_name="isread",
        ),
        migrations.RenameField(
            model_name="privatechatmessage",
            old_name="created_at",
            new_name="createdat",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="date_of_birth",
            new_name="dateofbirth",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="full_name",
            new_name="fullname",
        ),
        migrations.RenameField(
            model_name="settlement",
            old_name="created_at",
            new_name="createdat",
        ),
        migrations.RenameField(
            model_name="settlement",
            old_name="is_settled",
            new_name="issettled",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="deleted_by",
        ),
        migrations.RemoveField(
            model_name="group",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="decided_by",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="settlement",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="settlement",
            name="to_user",
        ),
        migrations.AddField(
            model_name="expense",
            name="deletedby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deletedexpenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="createdby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="createdgroups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="decidedby",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leaverequestsdecided",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="fromuser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sentnotifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="settlement",
            name="fromuser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settlementsmade",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="settlement",
            name="touser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settlementsreceived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="users",
            field=models.ManyToManyField(
                related_name="privatechatrooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="receipt",
            field=models.ImageField(blank=True, null=True, upload_to="receipts"),
        ),
        migrations.AlterField(
            model_name="group",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="grouppics"),
        ),
        migrations.AlterField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="paymatesgroups",
                related_query_name="paymatesgroup",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="groupchatmessage",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatmessages",
                to="core.group",
            ),
        ),
        migrations.AlterField(
            model_name="groupchatmessage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="chatimages"),
        ),
        migrations.AlterField(
            model_name="groupchatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatmessages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaverequests",
                to="core.group",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaverequests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("invite", "Group Invite"),
                    ("joined", "User Joined"),
                    ("left", "User Left"),
                    ("leaverequest", "Leave Request"),
                    ("leaveapproved", "Leave Approved"),
                    ("leaverejected", "Leave Rejected"),
                    ("expensedeleted", "Expense Deleted"),
                    ("groupchat", "Group Chat Message"),
                    ("privatechat", "Private Chat Message"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="privatechatmessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="privatechatimages"
            ),
        ),
        migrations.AlterField(
            model_name="privatechatmessage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="privatemessages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profilepics"),
        ),
    ]
